<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5cc31c7b2283f',
	'title' => 'Button',
	'fields' => array(
		array(
			'key' => 'field_5cc31d8d51bd2',
			'label' => 'Link',
			'name' => 'link',
			'type' => 'link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
		),
		array(
			'key' => 'field_5cc31f33041fa',
			'label' => 'Button Style',
			'name' => 'button_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'btn-primary' => 'Primary',
				'btn-secondary' => 'Secondary',
				'btn-success' => 'Success',
				'btn-danger' => 'Danger',
				'btn-warning' => 'Warning',
				'btn-info' => 'Info',
				'btn-light' => 'Light',
				'btn-dark' => 'Dark',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'Primary',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5cc31f5f041fb',
			'label' => 'Button Size',
			'name' => 'button_size',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Regular' => 'Regular',
				'btn-lg' => 'Large',
				'btn-sm' => 'Small',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'Regular',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5cc31fc3041fc',
			'label' => 'Block / Full Width',
			'name' => 'block_full_width',
			'type' => 'checkbox',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'btn-block' => 'Full Width',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
			'save_custom' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/bs-button',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
